### ISSUE TITLE
Can't import on Android Studio project.

### ISSUE THREAD

**Issue by ppamorim** [frakbot/GlowPadBackport#14]
If I add this library on my project, it broke my build.

**Comment by rock3r** [comment]
Can you please explain what you're doing and what's going on? Can't really tell much from this half sentence.

**Comment by mynavy** [comment]
Cant import too , im getting: 
Error:(48, 13) Failed to resolve: net.frakbot:glowpadbackport:2.1.1

**Comment by mynavy** [comment]
looks like thers something with net.frakbot 

i tryied to import  compile 'net.frakbot.glowpadbackport:glowpadbackport:2.1.0'

and it works

**Comment by nickaein-a** [comment]
+1

**Comment by cuongloveit** [comment]
Me too. Who can help me...

**Comment by cmendes0101** [comment]
Try adding this in build.gradle:
repositories {
    maven {
        url  "http://dl.bintray.com/frakbot/maven" 
    }
}

Or you can manually build and create the couple files needed for keystore and local.properties.

**Comment by cuongloveit** [comment]
ok tks. let me try it :)

**Comment by rock3r** [comment]
The package is on `jCenter`... https://bintray.com/bintray/jcenter?filterByPkgName=GlowPadBackport

**Comment by rock3r** [comment]
If you click on the "Set me up" link on Bintray you'll see that you need to do what @cmendes0101 has said already. Unfortunately for some reason publishing it to jCenter without linking it to Maven Central makes it not resolve sometimes... which is weird. But at this time I can't get it linked to Maven central because JFrog are putting up some (valid) issues that take too much time to solve.
